version: '3.9'

services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: DPZ4ZCtygy5rGQRMjkp1DkD6OuAucZtAwzeO6rcWg0
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./postgres_init:/app
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.8
    volumes:
      - ./redis:/data

  bank:
    platform: linux/amd64
    image: ghcr.io/web-programming-fall-2022/airline-bank:v1.0.0
    environment:
      DB_NAME: bank
      DB_USER: postgres
      DB_PASSWORD: DPZ4ZCtygy5rGQRMjkp1DkD6OuAucZtAwzeO6rcWg0
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    platform: linux/amd64
    image: ghcr.io/web-programming-fall-2022/airline-auth:v1.0.5
    volumes:
      - ./auth/config.yml:/app/config.yml:ro
    command:
      - ./aauth
      - serve
      - -c
      - /app/config.yml
    depends_on:
      postgres:
        condition: service_healthy

  ticket:
    platform: linux/amd64
    image: ghcr.io/web-programming-fall-2022/airline-ticket:v1.0.0
    volumes:
      - ./ticket/.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    
  
  frontend:
    platform: linux/amd64
    image: ghcr.io/web-programming-fall-2022/airline-frontend:v0.0.0
    depends_on:
      - auth
      - ticket

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - auth
      - ticket

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    depends_on:
      - ticket
