env: production

log:
  level: debug

server:
  port: 50051
  host: 0.0.0.0

httpServer:
  port: 8080

prometheus:
  enabled: true
  host: 0.0.0.0
  port: 8000

redis:
  addr: localhost:6379

jwt:
  secret: gMRL7Iwo7mIg6CXt2DSS1iMe8sEvTMJkZDrrd+AGEh4WVL+dEPkgJIFtujcBvN3C
  auth_token_expire: 3600
  refresh_token_expire: 86400

main_db:
  host: postgres
  port: 5432
  username: postgres
  password: DPZ4ZCtygy5rGQRMjkp1DkD6OuAucZtAwzeO6rcWg0
  db_name: auth
